### ISSUE TITLE
X68000 core needs some love

### ISSUE THREAD

**Issue by thehughhefner** [MiSTer-devel/X68000_MiSTer#2]
Hi @sorgelig.
The X68000 core on the MiSTer unfortunately is incomplete and is missing lots of things. Do you have any plans to fix this core?

**Comment by sorgelig** [comment]
Sometime ago i've cleaned this repo and update to latest at that time framework in order to help original developer to continue to develop it.
I never had this system myself and i don't speak Japanese (all SW/HW info in Japanese), so i cannot help much with development of this core.

**Comment by denisbr** [comment]
I think this very generic and unspecific issue can be closed now?
