### ISSUE TITLE
Add support for 10 Mhz speed

### ISSUE THREAD

**Issue by TimeWarpGamer** [MiSTer-devel/X68000_MiSTer#26]
It appears that the core by default sets speed at 16 Mhz, which is fine for most games, but there's a substantial number that will not properly launch, or play with glitches (i.e. way too fast) unless you use 10 Mhz.  Would it be possible to add 10 Mhz as an optional setting for games?  I guess another way to approach it would be to just set certain games to run at the correct 10 Mhz speed.  This page covers this issue: https://pcbiroiro.blogspot.com/2015/06/x68000-games-tested-at-16mhz.html.

And in my own testing, I've also noticed that the following also seem to need 10 Mhz:
Image Fight
Sabnack

Happy to help test games if you have new core builds for this issue :-)

**Comment by birdybro** [comment]
Just talked to one of the devs of the core, it's already running at 10MHz and the turbo is 20MHz. So these bugs must be caused by something else. The core doesn't support 16MHz mode.

**Comment by TimeWarpGamer** [comment]
Oh wow, thanks for the quick response.  Had been a while since I tested them; been slow on getting the feedback here.  I'll test again, and get back to y'all.  Take care!

**Comment by TimeWarpGamer** [comment]
I re-examined this today, and either things evolved over time to address issues, or I was totally off in my original assessment.  Anyway, you can close this ticket.  Sorry to clog up the queue with a probably non-existent issue.  Take care!

**Comment by birdybro** [comment]
You can close the ticket yourself if you want to, only the repo owners can close the tickets. It's a button just below the comment box "Close Issue". :)

**Comment by TimeWarpGamer** [comment]
Learning, thanks @birdybro!
