### ISSUE TITLE
Text shimmers/wiggles/jitters with VGA monitor

### ISSUE THREAD

**Issue by dbenoy** [MiSTer-devel/X68000_MiSTer#32]
Video: https://www.youtube.com/watch?v=_1RKk1HEeY4
You can see artifacts from the vertical sync which are not visible in person. But the horizontal wiggling is very conspicuous in person.
I haven't tried any games yet.
The problem isn't present on the HDMI output.

Monitor: IBM E74 connected directly to VGA with vga_scaler=0

**Comment by sorgelig** [comment]
please see this: https://github.com/MiSTer-devel/X68000_MiSTer/issues/33
The answer is the same: you have to use vga_scaler=1 for this core if you want to use VGA output.

**Comment by dbenoy** [comment]
That's very unfortunate. That will cause visual artifacts of its own when converting between resolutions.
But if it's not supported, then it's not supported. Thanks for taking a look :)
